platform :ios, '9.0'

# Uncomment this line if you're using Swift
# use_frameworks!

target 'Runner' do
  # Flutter pod
  use_frameworks!
  pod 'Flutter', :path => '../'
  # ... other pods ...

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
